version: '3'

services:
  planner:
    build:
      context: ./planner
      dockerfile: Dockerfile-planner
    ports:
      - "3000:3000"
    networks:
      - js-net

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile-worker
    ports:
      - "8080:8080"
    networks:
      - js-net
    # scale: 4
networks:
  js-net:
    driver: bridge